### PR TITLE
Fix mistake in policy

### PR DESCRIPTION
**Pull request by ramses999**
## what
Fix mistake in policy

## why
The policy is created simply by ARN without the ":" construct, which is necessary to create the correct policy for the role.
Without this ":" construct, the policy is created, but it does not work correctly.
This error was discovered when I tried to create a cloudwatch group in the cloudtrail module.
I got the response "Error: Error updating CloudTrail: InvalidCloudWatchLogsLogGroupArnException: Access denied. Verify in IAM that the role has adequate permissions."
After studying the code, I realized that I need to add the construction ":*" in a couple of lines.
My solution looks like this, I need to replace the lines in [file](https://github.com/cloudposse/terraform-aws-cloudwatch-logs/blob/master/iam.tf) :

This line:
join("", aws_cloudwatch_log_group.default.*.arn),
replaced by
"${join("", aws_cloudwatch_log_group.default.*.arn)}:*"
You need to do this in both identical lines.

Perhaps you can suggest a better solution, I'm new to terraforming.

## references
https://github.com/cloudposse/terraform-aws-cloudwatch-logs/issues/37
https://github.com/cloudposse/terraform-aws-cloudwatch-logs/blob/master/iam.tf#L55

### CODE REVIEW

**Review by nitrocode — DISMISSED** [review]

**Comment by ramses999** [comment]
@nitrocode  
Hello, "All checks have passed"

**Comment by ramses999** [comment]
@nitrocode I've been using this fix in a production environment for a couple of months now. It is correct.

**Comment by ramses999** [comment]
@nitrocode I've been using this fix in a production environment for a couple of months now. It is correct.

**Review by nitrocode — APPROVED** [review]

**Pull request merged**
